info:
  build:
    artifact: ubot-harsh-portfolio
    name: ubot-harsh-portfolio
    description: ubot-harsh-portfolio
    version: '@project.version@'

server:
  port: 8080
  
security:
  user:
    password: null
  basic:
    enabled: false
 
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.harshbits.ubot: DEBUG 
    
intentTypeList:
  ignoreIntents: smalltalk
  
dialog-flow.auth-token: e224271a102548418eac29e794706a44
